export { default as email } from './email.png';
export { default as finder } from './finder.png';
export { default as github } from './github.png';
export { default as instagram } from './instagram.png';
export { default as linkedin } from './linkedin.png';
export { default as paypal } from './paypal.png';
export { default as resume } from './resume.png';
export { default as terminal } from './terminal.png';
export { default as venmo } from './venmo.png';
